heat_set:
  target:
    entity:
      integration: eight_sleep
      domain: sensor
  fields:
    duration:
      required: true
      selector:
        number:
          min: 0
          max: 28800
          unit_of_measurement: seconds
    target:
      required: true
      selector:
        number:
          min: -100
          max: 100
          unit_of_measurement: "°"
    sleep_stage:
      required: true
      default: current
      selector:
        select:
          mode: dropdown
          options:
            - label: Set Current Temperature
              value: current
            - label: Set Bedtime Temperature
              value: bedTimeLevel
            - label: Set Early Temperature
              value: initialSleepLevel
            - label: Set Late Temperature
              value: finalSleepLevel
heat_increment:
  target:
    entity:
      integration: eight_sleep
      domain: sensor
  fields:
    target:
      required: true
      selector:
        number:
          min: -100
          max: 100
          unit_of_measurement: "°"
side_off:
  target:
    entity:
      integration: eight_sleep
      domain: sensor
side_on:
  target:
    entity:
      integration: eight_sleep
      domain: sensor
alarm_snooze:
  target:
    entity:
      integration: eight_sleep
      domain: sensor
  fields:
    duration:
      required: true
      selector:
        number:
          min: 1
          max: 1440
          unit_of_measurement: minutes
alarm_stop:
  target:
    entity:
      integration: eight_sleep
      domain: sensor
alarm_dismiss:
  target:
    entity:
      integration: eight_sleep
      domain: sensor
away_mode_start:
  target:
    entity:
      integration: eight_sleep
      domain: sensor
away_mode_stop:
  target:
    entity:
      integration: eight_sleep
      domain: sensor
prime_pod:
  target:
    entity:
      integration: eight_sleep
      domain: sensor
set_bed_side:
  target:
    entity:
      integration: eight_sleep
      domain: sensor
  fields:
    bed_side_state:
      required: true
      default: solo
      selector:
        select:
          mode: dropdown
          options:
            - label: Both
              value: solo
            - label: Left
              value: left
            - label: Right
              value: right
health_check:
  fields:
    detailed:
      required: false
      default: false
      selector:
        boolean:
performance_check:
  fields:
    include_cache:
      required: false
      default: true
      selector:
        boolean:
    include_connection:
      required: false
      default: true
      selector:
        boolean:
clear_cache:
  fields:
    confirm:
      required: false
      default: false
      selector:
        boolean:
error_report:
  fields:
    include_history:
      required: false
      default: true
      selector:
        boolean:
    include_diagnostics:
      required: false
      default: false
      selector:
        boolean:
error_notification:
  fields:
    error_type:
      required: true
      selector:
        text:
    entity_id:
      required: false
      default: ""
      selector:
        text:
    error_details:
      required: false
      default: ""
      selector:
        text:
    severity:
      required: false
      default: warning
      selector:
        select:
          mode: dropdown
          options:
            - label: Info
              value: info
            - label: Warning
              value: warning
            - label: Error
              value: error